### ISSUE TITLE
milvus-lite?

### ISSUE THREAD

**Issue by yuanjie-ai** [gusye1234/nano-graphrag#10]
milvus-lite?

**Comment by Hongru0306** [comment]
我也遇到了相同的问题，这好像是milvus-lite官方包不支持windows，目前这个包还在开发https://github.com/milvus-io/milvus-lite/issues/176

**Comment by gusye1234** [comment]
0af4ca35d03fd2f0b6efd4fcb8c16fa6 已经把milvus-lite从默认配置中拿出来了 下个版本里就不会默认使用了
