### ISSUE TITLE
use ollama glm4:latest(9b) can't extract any entities

### ISSUE THREAD

**Issue by flike** [gusye1234/nano-graphrag#21]
```
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
⠹ Processed 42 chunks, 0 entities(duplicated), 0 relations(duplicated)
WARNING:nano-graphrag:Didn't extract any entities, maybe your LLM is not working
WARNING:nano-graphrag:No new entities found
INFO:nano-graphrag:Writing graph with 0 nodes, 0 edges
indexing time: 260.7695245742798
INFO:nano-graphrag:Load KV full_docs with 0 data
INFO:nano-graphrag:Load KV text_chunks with 0 data
INFO:nano-graphrag:Load KV llm_response_cache with 168 data
INFO:nano-graphrag:Load KV community_reports with 0 data
INFO:nano-graphrag:Loaded graph from ./nano_graphrag_cache_ollama_TEST/graph_chunk_entity_relation.graphml with 0 nodes, 0 edges
INFO:nano-vectordb:Load (0, 1536) data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': './nano_graphrag_cache_ollama_TEST/vdb_entities.json'} 0 data
Sorry, I'm not able to provide an answer to that question.
```

How Can I make it work ? 
Thanks

**Comment by flike** [comment]
How can I print out each request I send to ollama, so I can manually debug it to further locate the problem

**Comment by flike** [comment]
I Print the reponse,such like this:
```
In this passage from Charles Dickens' "A Christmas Carol," Scrooge is preparing for bed and encounters several eerie occurrences:

1. **The Staircase**: Scrooge describes the procession of his own funeral as if it were real, even though he is alive. He is carrying a hearse, which he guides up the staircase with the splinter-bar towards the wall.

2. **Darkness and Security**: Scrooge enjoys the darkness and feels secure in his home, so much so that he locks himself in before going to bed.

3. **Checking His Rooms**: Before closing his door, Scrooge goes through his rooms to ensure everything is as it should be, including checking under furniture and making sure no one is hiding.

4. **The Lumber Room**: The passage mentions the items in Scrooge's lumber room: an old fire-guard, shoes, two fish baskets, a washing stand on three legs, and a poker.

5. **The Bell**: Suddenly, a bell that had been hanging in the room begins to swing with a strange, inexplicable dread, followed by a clanking noise as if someone is dragging a chain, which Scrooge associates with ghosts.

6. **Marley's Ghost**: The bells cease, and the ghost of Marley enters the room. The fire leaped up in reaction, indicating that the presence of Marley is real.

7. **The Chain**: Scrooge hears the sound of chains dragging closer to his door, which reinforces the idea that Marley's spirit has a chain linked to it, symbolizing the bondage of his past mistakes and his need to warn Scrooge.

8. **Scrooge's Skepticism**: Despite the evidence, Scrooge initially doubts the reality of the ghost and tries to convince himself it is just "humbug."

The passage is setting up for the appearance of Marley's Ghost, which will serve as the first warning to Scrooge about the consequences of his actions and his neglectful attitude towards others.
```

**Comment by akai-shuuichi** [comment]
> I Print the reponse,such like this:
> 
> ```
> In this passage from Charles Dickens' "A Christmas Carol," Scrooge is preparing for bed and encounters several eerie occurrences:
> 
> 1. **The Staircase**: Scrooge describes the procession of his own funeral as if it were real, even though he is alive. He is carrying a hearse, which he guides up the staircase with the splinter-bar towards the wall.
> 
> 2. **Darkness and Security**: Scrooge enjoys the darkness and feels secure in his home, so much so that he locks himself in before going to bed.
> 
> 3. **Checking His Rooms**: Before closing his door, Scrooge goes through his rooms to ensure everything is as it should be, including checking under furniture and making sure no one is hiding.
> 
> 4. **The Lumber Room**: The passage mentions the items in Scrooge's lumber room: an old fire-guard, shoes, two fish baskets, a washing stand on three legs, and a poker.
> 
> 5. **The Bell**: Suddenly, a bell that had been hanging in the room begins to swing with a strange, inexplicable dread, followed by a clanking noise as if someone is dragging a chain, which Scrooge associates with ghosts.
> 
> 6. **Marley's Ghost**: The bells cease, and the ghost of Marley enters the room. The fire leaped up in reaction, indicating that the presence of Marley is real.
> 
> 7. **The Chain**: Scrooge hears the sound of chains dragging closer to his door, which reinforces the idea that Marley's spirit has a chain linked to it, symbolizing the bondage of his past mistakes and his need to warn Scrooge.
> 
> 8. **Scrooge's Skepticism**: Despite the evidence, Scrooge initially doubts the reality of the ghost and tries to convince himself it is just "humbug."
> 
> The passage is setting up for the appearance of Marley's Ghost, which will serve as the first warning to Scrooge about the consequences of his actions and his neglectful attitude towards others.
> ```

没有按照格式输出，换个模型吧
