### ISSUE TITLE
The progress of intergrating neo4j

### ISSUE THREAD

**Issue by Dorbmon** [gusye1234/nano-graphrag#38]
Hi,
Thank you for your excellent work. I am curious about the progress on integrating Neo4j and also vector databases. If the project is still in its early stages, I would be interested in taking on this task.

**Comment by gusye1234** [comment]
Thanks for the interests! 
I'm still looking at Neo4j now. Neo4j will be a GraphStorage and requires some efforts.
In the other way, VectorDatabase's integration is relatively easy. For example, in #2 , some of them requires pg-vector as the backend. Maybe you can start with this.

And yes, `nano-graphrag` is absolutely on its early-stage. Check out our ROADMAP and maybe add some things you find interesting

**Comment by Dorbmon** [comment]
OK. I will take a try. Thanks.
