### ISSUE TITLE
我换了一个gte模型，然后报了一个json的错误

### ISSUE THREAD

**Issue by saltyfish-kiri** [gusye1234/nano-graphrag#42]
**问这个问题前，我想询问一下gte模型的效果是不是会显著影响RAG的质量呢，如果没什么影响，那我就不换gte模型了**

**下面是换完gte模型的情况：
最下面是我修改的using_deepseek_as_llm.py代码，简单来说我就是把using_local_embedding_model.py里面的方法抄过来了，加了一个**
EMBED_MODEL = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2", cache_folder=WORKING_DIR, device="cpu"
)

@wrap_embedding_func_with_attrs(
    embedding_dim=EMBED_MODEL.get_sentence_embedding_dimension(),
    max_token_size=EMBED_MODEL.max_seq_length,
)
async def local_embedding(texts: list[str]) -> np.ndarray:
    return EMBED_MODEL.encode(texts, normalize_embeddings=True)

**然后在GraphRAG里面指定embedding_func=local_embedding,因为网络不好openai老是断，所以只能用本地emb model了，不知道我这个改法是不是对的？**

**现在的问题是使用默认的gte模型是没问题的，但是改成**
`EMBED_MODEL = SentenceTransformer(
    "gte_sentence-embedding_multilingual-base", cache_folder=WORKING_DIR, device="cuda", trust_remote_code=True
)`
**之后，报了**
`INFO:nano-graphrag:Writing graph with 1310 nodes, 1772 edges
Traceback (most recent call last):
  File "C:\Users\MuDi\Downloads\nano-graphrag-main\nano-graphrag-main\examples\using_deepseek_as_llm.py", line 122, in <module>
    insert()
  File "C:\Users\MuDi\Downloads\nano-graphrag-main\nano-graphrag-main\examples\using_deepseek_as_llm.py", line 115, in insert
    rag.insert(FAKE_TEXT)
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\graphrag.py", line 181, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "C:\Users\MuDi\.conda\envs\torch\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\graphrag.py", line 291, in ainsert
    await generate_community_report(
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\_op.py", line 578, in generate_community_report
    this_level_communities_reports = await asyncio.gather(
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\_op.py", line 555, in _form_single_community_report
    data = use_string_json_convert_func(response)
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\_utils.py", line 37, in convert_response_to_json
    raise e from None
  File "C:\Users\MuDi\.conda\envs\torch\lib\site-packages\nano_graphrag\_utils.py", line 33, in convert_response_to_json
    data = json.loads(json_str)
  File "C:\Users\MuDi\.conda\envs\torch\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MuDi\.conda\envs\torch\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MuDi\.conda\envs\torch\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 26 column 10 (char 1938)

进程已结束，退出代码为 1`
[error.txt](https://github.com/user-attachments/files/17008187/error.txt)

**看起来是json有问题，但是我在WORKING_DIR里vdb_entities.json没有找到相关内容，难不成是因为内存太小爆内存了而且还没有保存出来吗**

import os
import logging
import time

import numpy as np
from openai import AsyncOpenAI
from nano_graphrag import GraphRAG, QueryParam
from nano_graphrag import GraphRAG, QueryParam
from nano_graphrag.base import BaseKVStorage
from nano_graphrag._utils import compute_args_hash

logging.basicConfig(level=logging.WARNING)
logging.getLogger("nano-graphrag").setLevel(logging.INFO)
from sentence_transformers import SentenceTransformer
from nano_graphrag._utils import wrap_embedding_func_with_attrs

DEEPSEEK_API_KEY = "sk-"
MODEL = "deepseek-chat"

async def deepseepk_model_if_cache(
    prompt, system_prompt=None, history_messages=[], **kwargs
) -> str:
    openai_async_client = AsyncOpenAI(
        api_key=DEEPSEEK_API_KEY, base_url="https://api.deepseek.com"
    )
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})

    hashing_kv: BaseKVStorage = kwargs.pop("hashing_kv", None)
    messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})
    if hashing_kv is not None:
        args_hash = compute_args_hash(MODEL, messages)
        if_cache_return = await hashing_kv.get_by_id(args_hash)
        if if_cache_return is not None:
            return if_cache_return["return"]

    response = await openai_async_client.chat.completions.create(
        model=MODEL, messages=messages, **kwargs
    )

    if hashing_kv is not None:
        await hashing_kv.upsert(
            {args_hash: {"return": response.choices[0].message.content, "model": MODEL}}
        )
    return response.choices[0].message.content

def remove_if_exist(file):
    if os.path.exists(file):
        os.remove(file)

WORKING_DIR = "nano_graphrag_cache_deepseek_西游记_iic"

EMBED_MODEL = SentenceTransformer(
    "gte_sentence-embedding_multilingual-base", cache_folder=WORKING_DIR, device="cuda", trust_remote_code=True
)
EMBED_MODEL = SentenceTransformer(
    "all-MiniLM-L6-v2", cache_folder=WORKING_DIR, device="cuda"
)

@wrap_embedding_func_with_attrs(
    embedding_dim=EMBED_MODEL.get_sentence_embedding_dimension(),
    max_token_size=EMBED_MODEL.max_seq_length,
)
async def local_embedding(texts: list[str]) -> np.ndarray:
    return EMBED_MODEL.encode(texts, normalize_embeddings=True)

def query():
    rag = GraphRAG(
        working_dir=WORKING_DIR,
        best_model_func=deepseepk_model_if_cache,
        cheap_model_func=deepseepk_model_if_cache,
        embedding_func=local_embedding,
    )
    print(
        rag.query(
            "故事的主旨是什么?", param=QueryParam(mode="global")
        )
    )

def insert():
    from time import time

    with open("../tests/西游记.txt", encoding="utf-8-sig") as f:
        FAKE_TEXT = f.read()

    remove_if_exist(f"{WORKING_DIR}/vdb_entities.json")
    remove_if_exist(f"{WORKING_DIR}/kv_store_full_docs.json")
    remove_if_exist(f"{WORKING_DIR}/kv_store_text_chunks.json")
    remove_if_exist(f"{WORKING_DIR}/kv_store_community_reports.json")
    remove_if_exist(f"{WORKING_DIR}/graph_chunk_entity_relation.graphml")

    rag = GraphRAG(
        working_dir=WORKING_DIR,
        enable_llm_cache=True,
        best_model_func=deepseepk_model_if_cache,
        cheap_model_func=deepseepk_model_if_cache,
        embedding_func=local_embedding,
    )
    start = time()
    rag.insert(FAKE_TEXT)
    print("indexing time:", time() - start)
    # rag = GraphRAG(working_dir=WORKING_DIR, enable_llm_cache=True)
    # rag.insert(FAKE_TEXT[half_len:])

if __name__ == "__main__":
    insert()
    t0=time.time()
    query()
    print(time.time()-t0)

**Comment by gusye1234** [comment]
看起来不是embedding模型的错误， 可能是deepseek模型有时候json输出不稳定导致的

**Comment by DeMoth-1** [comment]
> 看起来不是embedding模型的错误， 可能是deepseek模型有时候json输出不稳定导致的

有考虑添加json生成重试的逻辑吗

**Comment by saltyfish-kiri** [comment]
> 看起来不是embedding模型的错误， 可能是deepseek模型有时候json输出不稳定导致的

确实，再试一遍就好了，非常感谢
