### ISSUE TITLE
为什么local查询报错？

### ISSUE THREAD

**Issue by blueskydata** [gusye1234/nano-graphrag#45]
using_ollama_as_llm.py，为什么local查询报没有设置OpenAIError的错，既然使用了 ollama.AsyncClient() 和 本地嵌入，为什么还需要openai, 感到不可思议。

**Comment by gusye1234** [comment]
你用的是https://github.com/gusye1234/nano-graphrag/blob/main/examples/using_ollama_as_llm.py这个吗？
这里面没有覆盖embedding函数 默认的embedding函数是openai的

**Comment by blueskydata** [comment]
> 你用的是[https://github.com/gusye1234/nano-graphrag/blob/main/examples/using_ollama_as_llm.py这个吗？](https://github.com/gusye1234/nano-graphrag/blob/main/examples/using_ollama_as_llm.py%E8%BF%99%E4%B8%AA%E5%90%97%EF%BC%9F) 这里面没有覆盖embedding函数 默认的embedding函数是openai的
知道了，谢谢
