### ISSUE TITLE
使用llama3.1:8b的时候，出现警告：Didn't extract any entities, maybe your LLM is not working

### ISSUE THREAD

**Issue by blueskydata** [gusye1234/nano-graphrag#51]
INFO:nano-graphrag:[New Chunks] inserting 42 chunks
INFO:nano-graphrag:[Entity Extraction]...
⠹ Processed 42 chunks, 0 entities(duplicated), 0 relations(duplicated)
WARNING:nano-graphrag:Didn't extract any entities, maybe your LLM is not working
WARNING:nano-graphrag:No new entities found
INFO:nano-graphrag:Writing graph with 0 nodes, 0 edges
indexing time: 3.8695967197418213
是不是要更换LLM呢，以前使用graphrag的时候，使用llama3.1:8b也出错。

**Comment by gusye1234** [comment]
checkout docs/FAQ.md~ This is a common problem

**Comment by guanzy2012** [comment]
出现这个问题，程序自动停了怎么办

**Comment by 3244we** [comment]
你跑通llama了吗，能加个联系方式聊一下吗
