### ISSUE TITLE
Tokenizer报错

### ISSUE THREAD

**Issue by xxxxinobody** [gusye1234/nano-graphrag#62]
在using_llm_api_as_llm+ollama_embedding.py中将llm更换为glm API，embedding更换为huggingface模型，代码为：
![image](https://github.com/user-attachments/assets/080d91a9-74d8-491b-9f65-8902f5ad1d31)
![image](https://github.com/user-attachments/assets/831525af-2d80-4a29-aa4f-b0ac104aff39)

但是报错
![image](https://github.com/user-attachments/assets/513e0024-7588-4940-972f-4b6bb9e913fa)

**Comment by rangehow** [comment]
`pip install -U tiktoken`
