### ISSUE TITLE
The error in UTF-8 encoding when storing extracted Chinese entity names in vdb_entities.json.

### ISSUE THREAD

**Issue by zhouyujin** [gusye1234/nano-graphrag#63]
When I use all-MiniLM-L6-v2 as the local vector encoding model to store the extracted Chinese entities in vdb_entities.json, the content I see is as follows, which is the Unicode encoding of Chinese, not UTF-8 encoding. The encoding method for writing to the JSON file in _utils.py is "utf-8". Is it related to the vector model I chose? How should I modify it?

---------------------------------------------------
{"embedding_dim": 384, "data": [{"__id__": "ent-3823944778412382ad171c8152055cdd", "entity_name": "\"\u592a\u767d\u91d1\u661f\u674e\u957f\u5e9a\""}, {"__id__": "ent-d6bbc7e0fc25691f48df9a5550de5c64", "entity_name": "\"\u8001\u9e64\""}, {"__id__": "ent-71cc9a28268df396b25d165ae4b899a6", "entity_name": "\"\u542f\u660e\u6bbf\""},
……
---------------------------------------------------

**Comment by gusye1234** [comment]
Are you using the latest commit?

**Comment by zhouyujin** [comment]
Thank you for your reply, I just downloaded the latest source code before and  did not update the dependency packages inside. After installing the latest version of nano-vectordb, the problem is resolved.
