### ISSUE TITLE
Fail to extract Entity using ollama

### ISSUE THREAD

**Issue by v-shaoningli** [gusye1234/nano-graphrag#74]
Hi! Thanks for your light version of GraphRAG!

Here I use the `using_ollama_as_llm.py` in `example` with model `llama3.2:1b`, but got:

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/3d313d1f-c750-4191-9b36-6dd7f984940e">

It seems that LLMs are running without errors.
How can I solve that? Really thanks for your help!

**Comment by v-shaoningli** [comment]
Fixed with FAQ

**Comment by Arima-Kisho** [comment]
I had the same problem. Can you tell me how you solved it? Thank you very much
