### ISSUE TITLE
construction problem

### ISSUE THREAD

**Issue by qhlx** [gusye1234/nano-graphrag#83]
when i input the construction "pip install -e .", there is a error hint"ERROR: file:///Users/liuxiang/Desktop/nano-graphrag-main/nano_graphrag does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found." I can't find such files in that directory.

**Comment by gusye1234** [comment]
You maybe in the wrong dir. Make sure you're running the command in the root dir of this project, where `setup.py` is located

**Comment by qhlx** [comment]
thank you very much!
