### ISSUE TITLE
how to use local ollama model as llm and embedding

### ISSUE THREAD

**Issue by WangAo-0** [gusye1234/nano-graphrag#91]
how can i set api_url

**Comment by thundax-lyp** [comment]
see: examples/using_llm_api_as_llm+ollama_embedding.py

**Comment by WangAo-0** [comment]
> see: examples/using_llm_api_as_llm+ollama_embedding.py

but , I didn't find a place to set the ollama embedding url

**Comment by WangAo-0** [comment]
When the Ollama server is not on the same host, use export OLLAMA_HOST = "remote_addr" to set the URL
